import type {
  DomainGroup,
  EndpointInventory,
  ImplementedCommand,
  PhaseCount,
  RoadmapPhase,
  TargetCapability,
} from './types.js'

const PHASE_LABELS: Record<RoadmapPhase, string> = {
  'tier-0-read': 'Tier 0 — READ',
  'tier-1-draft': 'Tier 1 — DRAFT',
  'tier-2-write': 'Tier 2 — WRITE',
  deferred: 'Deferred',
}

const PHASE_ORDER: RoadmapPhase[] = ['tier-0-read', 'tier-1-draft', 'tier-2-write', 'deferred']

function actionLabel(action: ImplementedCommand['action']): string {
  return action ?? 'n/a'
}

export function groupByDomain(
  commands: ImplementedCommand[],
  targets: TargetCapability[],
): {domains: DomainGroup[]; phases: PhaseCount[]} {
  const domainNames = new Set<string>()
  for (const command of commands) domainNames.add(command.domain)
  for (const target of targets) domainNames.add(target.domain)

  const domains: DomainGroup[] = [...domainNames]
    .sort((a, b) => a.localeCompare(b))
    .map(domain => ({
      domain,
      implemented: commands
        .filter(command => command.domain === domain)
        .sort((a, b) => a.command.localeCompare(b.command)),
      targets: targets.filter(target => target.domain === domain).sort((a, b) => a.resource.localeCompare(b.resource)),
    }))

  // Phase rows count pending target capabilities only; shipped work is reported
  // per domain above rather than being assigned a tier.
  const phases: PhaseCount[] = PHASE_ORDER.map(phase => ({
    phase,
    targets: targets.filter(target => target.phase === phase).length,
  }))

  return {domains, phases}
}

export function buildInventory(commands: ImplementedCommand[], targets: TargetCapability[]): EndpointInventory {
  const {domains, phases} = groupByDomain(commands, targets)
  return {
    commands: [...commands].sort((a, b) => a.command.localeCompare(b.command)),
    targets: [...targets].sort((a, b) => a.domain.localeCompare(b.domain) || a.resource.localeCompare(b.resource)),
    domains,
    phases,
  }
}

export function renderInventory(inventory: EndpointInventory): string {
  const lines: string[] = []
  const xeroCommands = inventory.commands.filter(c => c.surface === 'direct-xero')
  const localCommands = inventory.commands.filter(c => c.surface !== 'direct-xero')

  lines.push('# Xero endpoint inventory')
  lines.push('')
  lines.push('<!-- Generated by `npm run inventory` from `src/commands`. Do not edit by hand. -->')
  lines.push('')
  lines.push(
    'This inventory is generated from the implemented command surface in `src/commands`.',
    '**Target rows are planned capabilities and are NOT yet implemented** — no command,',
    'flag, or endpoint behind them exists today. Implemented rows are the real CLI',
    'surface; gated commands preview by default, immediate commands execute directly,',
    'and the `target` kernel retains its optional guarded execution policy.',
    '',
  )

  const totalTargets = inventory.targets.length
  lines.push('## Summary')
  lines.push('')
  lines.push(
    `- Implemented commands: **${inventory.commands.length}** (${xeroCommands.length} reach the Xero API, ${localCommands.length} local/kernel/offline)`,
  )
  lines.push(`- Target capabilities not yet implemented: **${totalTargets}**`)
  lines.push(`- Xero domains touched: **${inventory.domains.length}**`)
  lines.push('')

  lines.push('| Domain | Implemented | Targets (not yet implemented) |')
  lines.push('|---|---|---|')
  for (const domain of inventory.domains) {
    lines.push(`| ${domain.domain} | ${domain.implemented.length} | ${domain.targets.length} |`)
  }
  lines.push('')

  lines.push('## Counts per roadmap phase')
  lines.push('')
  lines.push(
    'Phases follow the authority tiers retained by the roadmap v2 endpoint matrix.',
    'ADR-0012 makes the corresponding authority choices an operator decision, not a',
    'capability fence.',
    '',
  )
  lines.push('| Phase | Target capabilities pending |')
  lines.push('|---|---|')
  for (const phase of inventory.phases) {
    lines.push(`| ${PHASE_LABELS[phase.phase]} | ${phase.targets} |`)
  }
  lines.push('')

  for (const domain of inventory.domains) {
    lines.push(`### ${domain.domain}`)
    lines.push('')
    if (domain.implemented.length > 0) {
      lines.push('**Implemented**')
      lines.push('')
      lines.push('| Command | Surface | Action | Xero API methods |')
      lines.push('|---|---|---|---|')
      for (const command of domain.implemented) {
        const methods = command.xeroMethods.length > 0 ? command.xeroMethods.join(', ') : '—'
        lines.push(
          `| \`ledgerops ${command.command}\` | ${command.surface} | ${actionLabel(command.action)} | ${methods} |`,
        )
      }
    } else {
      lines.push('_No implemented commands._')
    }
    lines.push('')
    if (domain.targets.length > 0) {
      lines.push('**Target — not yet implemented**')
      lines.push('')
      lines.push('| Resource | Actions | Phase | Source |')
      lines.push('|---|---|---|---|')
      for (const target of domain.targets) {
        lines.push(
          `| ${target.resource} | ${target.actions.join(', ')} | ${PHASE_LABELS[target.phase]} | ${target.source} |`,
        )
      }
      lines.push('')
    }
  }

  return `${lines
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trimEnd()}\n`
}
